insert into especies(especie, idespecie)values('Roedor',  1);
insert into especies(especie, idespecie)values('Canino',  2);
insert into especies(especie, idespecie)values('Roedor',  3);
insert into especies(especie, idespecie)values('Réptil',  4);
insert into especies(especie, idespecie)values('Passaro',  5);
/*####################################################################################################*/
insert into racas(racas, idracas)values('Norwich Terrier', 15);
insert into racas(racas, idracas)values('Mastife', 16);
insert into racas(racas, idracas)values('ShihTzu', 17);
insert into racas(racas, idracas)values('Chow Chow', 18);
insert into racas(racas, idracas)values('Weimaraner', 19);
insert into racas(racas, idracas)values('Dandie Dinmont Terrier', 20);
insert into racas(racas, idracas)values('Buldogue Inglês', 21);
insert into racas(racas, idracas)values('Norfolk Terrier', 22);
insert into racas(racas, idracas)values('Lhasa Apso', 23);
insert into racas(racas, idracas)values('Grande Boiadeiro Suiço', 24);
insert into racas(racas, idracas)values('Doberman', 25);
insert into racas(racas, idracas)values('Airedale Terrier', 26);
insert into racas(racas, idracas)values('Skye Terrier', 27);
insert into racas(racas, idracas)values('Yorkshire Terrier', 28);
insert into racas(racas, idracas)values('Grifo da Bélgica', 29);
insert into racas(racas, idracas)values('Chow Chow', 30);
insert into racas(racas, idracas)values('Pastor Australiano', 31);
insert into racas(racas, idracas)values('Beagle', 32);
insert into racas(racas, idracas)values('Cairn Terrier', 33);
insert into racas(racas, idracas)values('Welsh Corgi (Pembroke', 34);
insert into racas(racas, idracas)values('Lhasa Apso', 35);
insert into racas(racas, idracas)values('West Highland White', 36);
insert into racas(racas, idracas)values('Collie', 37);
insert into racas(racas, idracas)values('Poodle', 38);
insert into racas(racas, idracas)values('Pastor Australiano', 39);
insert into racas(racas, idracas)values('Pastor Alemão', 40);
insert into racas(racas, idracas)values('Malamute do Alasca', 41);
insert into racas(racas, idracas)values('Chow Chow', 42);
insert into racas(racas, idracas)values('Silky Terrier', 43);
insert into racas(racas, idracas)values('West Highland White', 44);
insert into racas(racas, idracas)values('Norwich Terrier', 45);
insert into racas(racas, idracas)values('Lhasa Apso', 46);
insert into racas(racas, idracas)values('Affenpinscher', 47);
insert into racas(racas, idracas)values('Rottweiler', 48);
insert into racas(racas, idracas)values('Collie', 49);
insert into racas(racas, idracas)values('Galgo Escocês', 50);
insert into racas(racas, idracas)values('Poodle', 51);
insert into racas(racas, idracas)values('Border Collie', 52);
insert into racas(racas, idracas)values('Pastor Alemão', 53);
insert into racas(racas, idracas)values('Collie', 54);
insert into racas(racas, idracas)values('Yorkshire Terrier', 55);
insert into racas(racas, idracas)values('Basset Hound', 56);
insert into racas(racas, idracas)values('Coton de Tuléar', 57);
insert into racas(racas, idracas)values('Mastim Tibetano', 58);
insert into racas(racas, idracas)values('Papillon', 59);
insert into racas(racas, idracas)values('Lulu da Pomerânia', 60);
insert into racas(racas, idracas)values('West Highland White', 61);
insert into racas(racas, idracas)values('Bloodhound', 62);
insert into racas(racas, idracas)values('Welsh Corgi (Cardigan', 63);
insert into racas(racas, idracas)values('Mastim Napolitano', 64);
insert into racas(racas, idracas)values('Border Terrier', 65);
insert into racas(racas, idracas)values('Terra Nova', 66);
insert into racas(racas, idracas)values('Sem Raça Definida', 67);
insert into racas(racas, idracas)values('Coton de Tuléar', 68);
insert into racas(racas, idracas)values('Borzoi', 69);
insert into racas(racas, idracas)values('Whippet', 70);
insert into racas(racas, idracas)values('Buldogue Inglês', 71);
insert into racas(racas, idracas)values('Akita', 72);
insert into racas(racas, idracas)values('Bloodhound', 73);
insert into racas(racas, idracas)values('Jack Russell Terrier', 74);
insert into racas(racas, idracas)values('Golden Retriever', 75);
insert into racas(racas, idracas)values('Tosa', 76);
insert into racas(racas, idracas)values('Welsh Corgi (Pembroke', 77);
insert into racas(racas, idracas)values('Labrador Retriever', 78);
insert into racas(racas, idracas)values('Akita', 79);
insert into racas(racas, idracas)values('Coton de Tuléar', 80);
insert into racas(racas, idracas)values('Pastor Australiano', 81);
insert into racas(racas, idracas)values('Cão de Crista', 82);
insert into racas(racas, idracas)values('Tosa', 83);
insert into racas(racas, idracas)values('Welsh Corgi (Pembroke', 84);
insert into racas(racas, idracas)values('Greyhound', 85);
insert into racas(racas, idracas)values('Chesapeake Bay Retriever', 86);
insert into racas(racas, idracas)values('Jack Russell Terrier', 87);
insert into racas(racas, idracas)values('Collie', 88);
insert into racas(racas, idracas)values('Cane Corso', 89);
insert into racas(racas, idracas)values('Cão de Água', 90);
insert into racas(racas, idracas)values('Golden Retriever', 91);
insert into racas(racas, idracas)values('Bulmastife', 92);
insert into racas(racas, idracas)values('Chow Chow', 93);
insert into racas(racas, idracas)values('Dandie Dinmont Terrier', 94);
insert into racas(racas, idracas)values('Cane Corso', 95);
insert into racas(racas, idracas)values('Husky Siberiano', 96);
insert into racas(racas, idracas)values('Mastim Napolitano', 97);
insert into racas(racas, idracas)values('Bloodhound', 98);
insert into racas(racas, idracas)values('Bloodhound', 99);
insert into racas(racas, idracas)values('Pastor Alemão', 100);
insert into racas(racas, idracas)values('Chesapeake Bay Retriever', 101);
insert into racas(racas, idracas)values('Bobtail', 102);
insert into racas(racas, idracas)values('Chow Chow', 103);
insert into racas(racas, idracas)values('Leonberger', 104);
insert into racas(racas, idracas)values('American Staffordshire Terrier', 105);
insert into racas(racas, idracas)values('Cocker Spaniel Americano', 106);
insert into racas(racas, idracas)values('Bedlington Terrier', 107);
insert into racas(racas, idracas)values('Airedale Terrier', 108);
insert into racas(racas, idracas)values('Mastife', 109);
insert into racas(racas, idracas)values('Dachshund', 110);
insert into racas(racas, idracas)values('Husky Siberiano', 111);
insert into racas(racas, idracas)values('Bichon Frisé', 112);
insert into racas(racas, idracas)values('Boiadeiro Australiano', 113);
insert into racas(racas, idracas)values('Staffordshire Bull Terrier', 114);
insert into racas(racas, idracas)values('Bloodhound', 115);
insert into racas(racas, idracas)values('Terra Nova', 116);
insert into racas(racas, idracas)values('Chihuahua', 117);
insert into racas(racas, idracas)values('Airedale Terrier', 118);
insert into racas(racas, idracas)values('West Highland White', 119);
insert into racas(racas, idracas)values('Collie', 120);
insert into racas(racas, idracas)values('Whippet', 121);
insert into racas(racas, idracas)values('Leonberger', 122);
insert into racas(racas, idracas)values('Chihuahua', 123);
insert into racas(racas, idracas)values('Silky Terrier', 124);
insert into racas(racas, idracas)values('Terra Nova', 125);
insert into racas(racas, idracas)values('Pastor Alemão', 126);
insert into racas(racas, idracas)values('Xoloitzcuintli', 127);
insert into racas(racas, idracas)values('Dálmata', 128);
insert into racas(racas, idracas)values('Galgo Escocês', 129);
insert into racas(racas, idracas)values('Bloodhound', 130);
insert into racas(racas, idracas)values('Coton de Tuléar', 131);
insert into racas(racas, idracas)values('Whippet', 132);
insert into racas(racas, idracas)values('Mastife', 133);
insert into racas(racas, idracas)values('Pastor Australiano', 134);
insert into racas(racas, idracas)values('Tosa', 135);
insert into racas(racas, idracas)values('Skye Terrier', 136);
insert into racas(racas, idracas)values('Buldogue Francês', 137);
insert into racas(racas, idracas)values('Yorkshire Terrier', 138);
insert into racas(racas, idracas)values('Beagle', 139);
insert into racas(racas, idracas)values('Akita', 140);
insert into racas(racas, idracas)values('Chihuahua', 141);
insert into racas(racas, idracas)values('Mastim Tibetano', 142);
insert into racas(racas, idracas)values('Yorkshire Terrier', 143);
insert into racas(racas, idracas)values('Weimaraner', 144);
insert into racas(racas, idracas)values('Collie', 145);
insert into racas(racas, idracas)values('Chihuahua', 146);
insert into racas(racas, idracas)values('Pastor Alemão', 147);
insert into racas(racas, idracas)values('Grifo da Bélgica', 148);
insert into racas(racas, idracas)values('Boiadeiro Bernês', 149);
insert into racas(racas, idracas)values('King Charles', 150);
insert into racas(racas, idracas)values('Lhasa Apso', 151);
insert into racas(racas, idracas)values('Afegão Hound', 152);
insert into racas(racas, idracas)values('Lhasa Apso', 153);
insert into racas(racas, idracas)values('Papillon', 154);
insert into racas(racas, idracas)values('Welsh Corgi (Cardigan', 155);
insert into racas(racas, idracas)values('Coton de Tuléar', 156);
insert into racas(racas, idracas)values('Foxhound Inglês', 157);
insert into racas(racas, idracas)values('Mastim Tibetano', 158);
insert into racas(racas, idracas)values('King Charles', 159);
insert into racas(racas, idracas)values('Pug', 160);
insert into racas(racas, idracas)values('King Charles', 161);
insert into racas(racas, idracas)values('Papillon', 162);
insert into racas(racas, idracas)values('Mastim Napolitano', 163);
insert into racas(racas, idracas)values('Pastor Australiano', 164);
insert into racas(racas, idracas)values('Terrier Escocês', 165);
insert into racas(racas, idracas)values('Komondor', 166);
insert into racas(racas, idracas)values('American Staffordshire Terrier', 167);
insert into racas(racas, idracas)values('Doberman', 168);
insert into racas(racas, idracas)values('Dachshund', 169);
insert into racas(racas, idracas)values('Foxhound Inglês', 170);
insert into racas(racas, idracas)values('Greyhound', 171);
insert into racas(racas, idracas)values('Pastor Australiano', 172);
insert into racas(racas, idracas)values('Dandie Dinmont Terrier', 173);
insert into racas(racas, idracas)values('Mastife', 174);
insert into racas(racas, idracas)values('Bobtail', 175);
insert into racas(racas, idracas)values('Grande Boiadeiro Suiço', 176);
insert into racas(racas, idracas)values('Terra Nova', 177);
insert into racas(racas, idracas)values('Norwich Terrier', 178);
insert into racas(racas, idracas)values('Golden Retriever', 179);
insert into racas(racas, idracas)values('Foxhound Inglês', 180);
insert into racas(racas, idracas)values('Pastor Australiano', 181);
insert into racas(racas, idracas)values('Boston Terrier', 182);
insert into racas(racas, idracas)values('Bichon Frisé', 183);
insert into racas(racas, idracas)values('Dandie Dinmont Terrier', 184);
insert into racas(racas, idracas)values('Buldogue Francês', 185);
insert into racas(racas, idracas)values('Terrier Escocês', 186);
insert into racas(racas, idracas)values('Mastim Napolitano', 187);
insert into racas(racas, idracas)values('Doberman', 188);
insert into racas(racas, idracas)values('Pastor Alemão', 189);
insert into racas(racas, idracas)values('Border Terrier', 190);
insert into racas(racas, idracas)values('Boxer', 191);
insert into racas(racas, idracas)values('Fox Terrier (Pelo', 192);
insert into racas(racas, idracas)values('Beagle Harrier', 193);
insert into racas(racas, idracas)values('Afegão Hound', 194);
insert into racas(racas, idracas)values('Cairn Terrier', 195);
insert into racas(racas, idracas)values('Cocker Spaniel Americano', 196);
insert into racas(racas, idracas)values('Welsh Corgi (Pembroke', 197);
insert into racas(racas, idracas)values('Cocker Spaniel Americano', 198);
insert into racas(racas, idracas)values('Silky Terrier', 199);
/*####################################################################################################*/
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Clara', '2002-9-3', null, 27, 2, 15);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Aurora', '2065-11-15', null, 66, 2, 16);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Bianca', '2037-9-10', null, 56, 2, 17);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Lavínia', '2046-9-7', null, 36, 2, 18);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Alícia', '2055-4-14', null, 86, 2, 19);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2007-6-2', null, 25, 2, 20);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maitê', '2037-1-1', null, 40, 2, 21);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Samuel', '2087-1-24', null, 15, 2, 22);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Pedro', '2019-2-27', null, 72, 2, 23);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2054-2-4', null, 57, 2, 24);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Sophia', '2090-12-17', null, 40, 2, 25);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Enzo', '2066-10-26', null, 55, 2, 26);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gabriel', '2026-8-14', null, 81, 2, 27);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Valentina', '2013-8-27', null, 44, 2, 28);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2027-7-2', null, 72, 2, 29);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2036-11-11', null, 79, 2, 30);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Levi', '2007-1-13', null, 29, 2, 31);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2090-4-14', null, 31, 2, 32);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2095-12-20', null, 30, 2, 33);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Samuel', '2021-7-13', null, 11, 2, 34);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Théo', '2035-10-30', null, 6, 2, 35);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Heloise', '2091-12-25', null, 86, 2, 36);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Davi', '2083-6-30', null, 84, 2, 37);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luan', '2060-10-19', null, 57, 2, 38);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maya', '2073-1-6', null, 19, 2, 39);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2058-9-18', null, 25, 2, 40);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2096-9-17', null, 16, 2, 41);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Laura', '2092-12-9', null, 42, 2, 42);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2090-10-5', null, 60, 2, 43);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Heloise', '1990-4-6', null, 40, 2, 44);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Francisco', '2047-5-29', null, 39, 2, 45);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Letícia', '2003-10-16', null, 2, 2, 46);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2051-12-13', null, 88, 2, 47);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Raul', '2041-6-25', null, 76, 2, 48);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2080-5-11', null, 91, 2, 49);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Mariah', '2007-1-26', null, 83, 2, 50);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Enzo', '2025-1-1', null, 67, 2, 51);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gabriel', '2016-1-14', null, 9, 2, 52);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Mirella', '2037-2-15', null, 71, 2, 53);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gustavo', '2001-8-1', null, 63, 2, 54);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Allana', '2044-3-22', null, 15, 2, 55);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2005-11-25', null, 8, 2, 56);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Cauã', '2030-9-30', null, 18, 2, 57);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2028-9-5', null, 10, 2, 58);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2011-1-27', null, 7, 2, 59);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Henry', '2029-6-31', null, 61, 2, 60);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2095-9-2', null, 23, 2, 61);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Emanuelly', '2090-10-14', null, 84, 2, 62);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ian', '2050-6-2', null, 29, 2, 63);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gustavo', '2047-1-31', null, 16, 2, 64);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Davi', '2044-2-27', null, 79, 2, 65);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Mariah', '2091-11-17', null, 86, 2, 66);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2096-5-4', null, 89, 2, 67);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Lara', '2040-11-28', null, 50, 2, 68);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Valentina', '2099-11-30', null, 83, 2, 69);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2039-12-24', null, 0, 2, 70);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Joaquim', '2046-9-23', null, 17, 2, 71);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Carlos', '2100-6-5', null, 48, 2, 72);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Guilherme', '2053-3-8', null, 33, 2, 73);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Pedro', '2024-8-10', null, 82, 2, 74);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Mirella', '2098-9-18', null, 8, 2, 75);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2071-6-25', null, 56, 2, 76);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Nicole', '2057-4-7', null, 50, 2, 77);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2027-10-4', null, 40, 2, 78);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Emilly', '2095-1-1', null, 64, 2, 79);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Esther', '1996-7-14', null, 69, 2, 80);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2013-8-13', null, 58, 2, 81);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Yago', '2065-12-3', null, 86, 2, 82);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Caio', '2046-12-29', null, 5, 2, 83);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Carolina', '2088-11-14', null, 74, 2, 84);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Carlos', '2094-10-20', null, 56, 2, 85);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gustavo', '2094-12-30', null, 31, 2, 86);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Victor', '2045-7-31', null, 7, 2, 87);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Rafael', '2046-10-28', null, 84, 2, 88);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Carlos', '2017-9-21', null, 9, 2, 89);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Allana', '2044-8-4', null, 23, 2, 90);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Elisa', '2055-1-18', null, 21, 2, 91);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Thiago', '2012-9-25', null, 33, 2, 92);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Louise', '2059-2-9', null, 59, 2, 93);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Heloísa', '2045-2-20', null, 39, 2, 94);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Bento', '2043-6-14', null, 21, 2, 95);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Clara', '2076-2-17', null, 76, 2, 96);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ian', '2070-1-31', null, 41, 2, 97);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Mariana', '2099-3-7', null, 88, 2, 98);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Lorena', '2018-6-8', null, 63, 2, 99);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Miguel', '2053-7-15', null, 42, 2, 100);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Isadora', '2090-9-4', null, 85, 2, 101);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('João', '2047-2-1', null, 44, 2, 102);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Sarah', '2050-11-1', null, 47, 2, 103);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Milena', '2045-10-16', null, 60, 2, 104);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2036-10-24', null, 26, 2, 105);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Oliver', '2096-9-14', null, 72, 2, 106);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Helena', '2041-4-1', null, 1, 2, 107);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Clara', '1998-5-31', null, 18, 2, 108);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Danilo', '1990-2-22', null, 56, 2, 109);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ayla', '2066-12-20', null, 66, 2, 110);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2034-1-29', null, 63, 2, 111);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Arthur', '2046-7-2', null, 41, 2, 112);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Nicolas', '2022-1-29', null, 41, 2, 113);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Manuela', '2035-10-27', null, 87, 2, 114);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Felipe', '2011-2-7', null, 36, 2, 115);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Erick', '2048-9-20', null, 54, 2, 116);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Isabella', '2085-12-27', null, 47, 2, 117);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Thomas', '2048-2-17', null, 60, 2, 118);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Fernanda', '2028-7-22', null, 54, 2, 119);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gabrielly', '2003-11-27', null, 18, 2, 120);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maitê', '2016-5-30', null, 8, 2, 121);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2037-11-6', null, 39, 2, 122);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Bruno', '2059-9-23', null, 42, 2, 123);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ruan', '2069-2-11', null, 68, 2, 124);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Heloísa', '2066-12-5', null, 42, 2, 125);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Sophie', '2098-9-31', null, 19, 2, 126);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Guilherme', '2061-2-23', null, 41, 2, 127);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Thiago', '2073-6-22', null, 30, 2, 128);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Francisco', '2027-4-31', null, 20, 2, 129);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2078-12-8', null, 49, 2, 130);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Francisco', '2028-2-27', null, 2, 2, 131);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Kaique', '2002-9-23', null, 15, 2, 132);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luna', '2012-7-17', null, 12, 2, 133);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Yago', '2029-1-7', null, 10, 2, 134);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Gael', '2009-10-11', null, 87, 2, 135);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('João', '2010-1-27', null, 24, 2, 136);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Yago', '2027-2-23', null, 90, 2, 137);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2066-5-11', null, 5, 2, 138);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Enrico', '2037-2-4', null, 91, 2, 139);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Liz', '2048-4-31', null, 33, 2, 140);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Emanuelly', '2019-12-18', null, 27, 2, 141);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2086-11-16', null, 8, 2, 142);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Pedro', '2011-4-4', null, 49, 2, 143);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Laís', '2035-4-7', null, 11, 2, 144);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Eduarda', '2032-5-26', null, 16, 2, 145);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Bianca', '2033-9-31', null, 33, 2, 146);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Caleb', '2020-6-7', null, 57, 2, 147);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Enrico', '2067-3-20', null, 22, 2, 148);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Yuri', '2084-4-2', null, 79, 2, 149);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('João', '2017-8-11', null, 34, 2, 150);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2080-7-22', null, 77, 2, 151);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Malu', '2022-12-27', null, 69, 2, 152);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Clara', '2100-3-13', null, 52, 2, 153);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Analu', '2085-12-4', null, 35, 2, 154);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2005-5-1', null, 35, 2, 155);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2095-10-30', null, 46, 2, 156);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Clarice', '2085-2-13', null, 86, 2, 157);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2067-2-4', null, 80, 2, 158);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Aurora', '2092-10-22', null, 24, 2, 159);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Sophie', '2061-11-30', null, 14, 2, 160);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2040-5-9', null, 21, 2, 161);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Caleb', '2063-11-16', null, 20, 2, 162);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Heloise', '2075-11-19', null, 80, 2, 163);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Antônio', '2081-6-29', null, 82, 2, 164);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Henrique', '2063-2-3', null, 52, 2, 165);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Aurora', '2062-6-30', null, 28, 2, 166);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Allana', '2050-3-2', null, 21, 2, 167);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Oliver', '2014-10-7', null, 37, 2, 168);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ryan', '2065-1-10', null, 78, 2, 169);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Aurora', '2081-6-8', null, 66, 2, 170);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2006-9-11', null, 6, 2, 171);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('José', '2025-8-27', null, 84, 2, 172);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Lara', '2074-3-27', null, 13, 2, 173);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Arthur', '1995-8-15', null, 59, 2, 174);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ryan', '1991-3-28', null, 43, 2, 175);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Enrico', '2058-7-1', null, 78, 2, 176);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Alícia', '2059-5-26', null, 23, 2, 177);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Antonella', '1998-5-24', null, 57, 2, 178);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Clara', '2018-12-3', null, 56, 2, 179);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Amanda', '2093-10-10', null, 85, 2, 180);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2081-9-29', null, 37, 2, 181);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2043-8-4', null, 53, 2, 182);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('João', '2020-5-27', null, 80, 2, 183);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Oliver', '2064-5-2', null, 8, 2, 184);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Théo', '2062-1-10', null, 0, 2, 185);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Júlia', '2048-1-11', null, 8, 2, 186);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Antonella', '2073-7-2', null, 29, 2, 187);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Joana', '1996-4-20', null, 11, 2, 188);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Helena', '2013-10-9', null, 25, 2, 189);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2002-1-3', null, 36, 2, 190);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2069-3-3', null, 64, 2, 191);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2089-8-27', null, 75, 2, 192);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Maria', '2092-10-19', null, 87, 2, 193);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Luiz', '2048-2-14', null, 32, 2, 194);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Arthur', '2011-4-28', null, 44, 2, 195);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Analu', '2089-6-21', null, 68, 2, 196);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Henrique', '2061-8-30', null, 14, 2, 197);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ana', '2024-8-20', null, 44, 2, 198);
insert into animal(nome, datanascimento, dtulttrat, idracas, idespecie, idanimal)values('Ian', '2083-2-23', null, 71, 2, 199);
/*####################################################################################################*/
